### ISSUE TITLE
My process was force terminated, when i restart it, i can't offline the previous url without execute online beforehand.

### ISSUE THREAD

**Issue by jactorew** [alibaba/dubbo#1187]
如题
如果应用（redis+dubbo）进程在挂掉前是online状态，意外挂掉后被重新拉起来，这时该引用可以正常提供服务，但如果不执行online操作直接执行offline是无法下线服务。debug后发现offline时判断了com.alibaba.dubbo.registry.support.ProviderInvokerWrapper#isReg，而isReg只在online、offline和export时设置了值，所以在没有执行online和export的情况下，offline无效。

**Comment by qinliujie** [comment]
I can not quite understand，What is the way to restart your service？

**Comment by jactorew** [comment]
继续跟踪，发现异常重启后，dubbo根本没有再次去注册服务，订阅的服务也是不存在的（timestamp不一样），后续去更新value也是无效的。

**Comment by jactorew** [comment]
@qinliujie 直接杀掉进程，或者idea重启应用即可复现。

**Comment by chickenlj** [comment]
`继续跟踪，发现异常重启后，dubbo根本没有再次去注册服务`
What do you mean by not register service when your applicatio restart?

**Comment by jactorew** [comment]
@chickenlj 每次重启（online状态下），com.alibaba.dubbo.registry.integration.RegistryProtocol#export第135行的register值是false，所以并没有去注册服务。

**Comment by jactorew** [comment]
@chickenlj 实际上是com.alibaba.dubbo.registry.integration.RegistryProtocol#getRegistedProviderUrl这个方法每次重启后都是生成新的url（timestamp不同），所以判断这个url是否注册返回的肯定是false，而false的情况下又不去注册。

**Comment by chickenlj** [comment]
Your application was force terminated, so previous url registered to registry can't be deleted (because of timestamp), the only way to unregister it is waiting for registry timeout and being unregistered automatically.

Even if you use `register=true`, dubbo handle all `register/unregister` automatically for you, the previous url still can't be unregistered til timeout. So i don't think this is not a problem of `online/offline`.

**Comment by jactorew** [comment]
@chickenlj 也就是说：对于online状态的应用异常重启后，如果不执行online直接执行offline是无法下线服务的，除非服务超时后重新注册的服务才能offline？
