### ISSUE TITLE
dubbo:protocol不填写port属性，并不会自动分配端口

### ISSUE THREAD

**Issue by liuwenbin-web** [alibaba/dubbo#228]
dubbo版本：2.5.3

描述：
<dubbo:protocol name="dubbo"></dubbo:protocol>
不设置port属性并不会自动分配端口，多个provider端口都为20880，会提示端口冲突，只有设置了port="-1"，才会自动分配端口。

报错信息：
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to bind NettyServer on /10.10.101.111:20880, cause: Failed to bind to: /0.0.0.0:20880

**Comment by justein** [comment]
文档中有说明，设置为-1才会自动分配

2016-04-13 

james_gosling 



发件人：liuwenbin-web <notifications@github.com>
发送时间：2016-04-13 17:35
主题：[alibaba/dubbo] dubbo:protocol不填写port属性，并不会自动分配端口 (#228)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送：

dubbo版本：2.5.3
描述：
/dubbo:protocol
不设置port属性并不会自动分配端口，多个provider端口都为20880，会提示端口冲突，只有设置了port="-1"，才会自动分配端口。
报错信息：
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to bind NettyServer on /10.10.101.111:20880, cause: Failed to bind to: /0.0.0.0:20880

**Comment by liuwenbin-web** [comment]
官网文档摘取：dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80 
如果配置为-1 或者 没有配置port，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控。

**Comment by teaey** [comment]
端口的设置逻辑

+ protocol的指定端口
+ provider的指定端口
+ 如果上面两个端口没有配置，或者配置得为零则使用协议的默认端口
+ 如果上面三条获得的端口为空或者端口非正数则使用一个随机端口

**Comment by gMan1990** [comment]
@teaey 
写-1的确会随机分配端口，但是当端口被占用好像不会继续找端口
